version: '3'

services:

  pkgbuild-updater:
    container_name: pkgbuild-updater
    environment:
      - SLEEP_DURATION=14400  # This sets the sleep duration to 4 hours in seconds
      - TOKEN_GITHUB=${TOKEN_GITHUB}
      - GITHUB_USER=frederikstroem
      - GIT_NAME=frederikstroem
      - GIT_EMAIL=git@katofln.com
    volumes:
      - ./updater.py:/home/builduser/updater.py
      - ./logs:/home/builduser/logs
    build:
      context: .
      args:
        - GIT_NAME=frederikstroem
        - GIT_EMAIL=git@katofln.com
        - GIT_REPO=git@github.com:frederikstroem/PKGBUILDs.git
    ulimits:
      nofile:
        soft: 1024
        hard: 524288
