name: Update PKGBUILD
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.11

      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch all history so we can push to other branches

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests gitpython PyGithub

      - name: Run update script
        run: python update_and_test_pkgbuilds.py
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_USER: ${{ github.repository_owner }}
