name: PKGBUILD Updater
on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight
    # - cron: '0 0 */3 * *'  # Run every three days at midnight
  workflow_dispatch:  # Allow manual triggering of the workflow

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          docker pull archlinux:latest
          docker run -d --name arch-container -v ${PWD}:/workdir -w /workdir archlinux:latest sleep infinity

      - name: Install dependencies inside Arch container
        run: |
          docker exec arch-container bash -c "pacman -Syu --noconfirm base-devel git python-pip fakeroot binutils"
          docker exec arch-container bash -c "pip install requests gitpython PyGithub"

      - name: Run update script
        run: docker exec arch-container bash -c "python update_and_test_pkgbuilds.py"
        env:
          TOKEN_GITHUB: ${{ secrets.TOKEN_GITHUB }}
          GITHUB_USER: ${{ github.repository_owner }}

      - name: Cleanup Docker container
        if: always()
        run: docker rm -f arch-container
